/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * b14.java
 *
 * Created on Aug 30, 2014, 12:19:14 PM
 */

/**
 *
 * @author Student
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class b14 extends javax.swing.JFrame {

    /** Creates new form b14 */
    public b14() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        ddcn = new javax.swing.JButton();
        showdth = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        dccn = new javax.swing.JButton();
        show1dth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48));
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("freecharge.");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "debitcardno"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "creditcardno"
            }
        ));
        jScrollPane2.setViewportView(tb2);

        jLabel2.setText("DEBIT CARD...!!");

        jLabel3.setText("ENTER DEBIT CARD NO");

        ddcn.setBackground(new java.awt.Color(0, 0, 204));
        ddcn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        ddcn.setForeground(new java.awt.Color(0, 102, 102));
        ddcn.setText("PROCEED");
        ddcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddcnActionPerformed(evt);
            }
        });

        showdth.setBackground(new java.awt.Color(0, 0, 204));
        showdth.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        showdth.setForeground(new java.awt.Color(0, 255, 204));
        showdth.setText("SHOW");
        showdth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdthActionPerformed(evt);
            }
        });

        jLabel4.setText("CREDIT CARD...!!");

        jLabel5.setText("ENTER CREDIT CARD NO");

        dccn.setBackground(new java.awt.Color(0, 0, 204));
        dccn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        dccn.setForeground(new java.awt.Color(0, 51, 51));
        dccn.setText("PROCEED");
        dccn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dccnActionPerformed(evt);
            }
        });

        show1dth.setBackground(new java.awt.Color(0, 0, 255));
        show1dth.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        show1dth.setForeground(new java.awt.Color(0, 204, 204));
        show1dth.setText("SHOW");
        show1dth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show1dthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(484, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(ddcn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(showdth)
                .addGap(425, 425, 425))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(187, 187, 187)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3)
                        .addGap(173, 173, 173)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(dccn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(show1dth)
                        .addGap(127, 127, 127)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(563, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(260, 260, 260))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ddcn)
                            .addComponent(showdth))
                        .addGap(232, 232, 232)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dccn)
                            .addComponent(show1dth))))
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-929)/2, (screenSize.height-614)/2, 929, 614);
    }// </editor-fold>//GEN-END:initComponents

    private void showdthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdthActionPerformed
DefaultTableModel model=(DefaultTableModel)tb1.getModel();
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/yatharth","root","abc");
    Statement stmt=con.createStatement();
    String query="Select * FROM dthdebitcardnumber;";
    ResultSet rs=stmt.executeQuery(query);
    while(rs.next()){
        String dcn=rs.getString("debitcardnumber");
model.addRow(new Object[]{dcn});
    }
     rs.close();
     stmt.close();
     con.close();
}
catch(Exception e)
    {
    JoptionPane.showMessageDialog(null,"Error in connectivity");
}
// TODO add your handling code here:
    }//GEN-LAST:event_showdthActionPerformed

    private void ddcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddcnActionPerformed
String str=t1.getText();
if(str.isEmpty()){
JOptionPane.showMessageDialog(null,"Please enter your debitcardno");

}
else
{


 DefaultTableModel model=(DefaultTableModel)tb1.getModel();
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/yatharth","root","abc");
    Statement stmt=con.createStatement();
    String query="Insert into dthdebitcardnumber values '"+str+"';";
stmt.executeUpdate(query);
}
    catch(Exception e)
    {
    JoptionPane.showMessageDialog(null,"Error in connectivity");
}


     this.dispose();
b10 object = new b10();
object.setVisible(true);

}
// TODO add your handling code here:
    }//GEN-LAST:event_ddcnActionPerformed

    private void show1dthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show1dthActionPerformed
DefaultTableModel model=(DefaultTableModel)tb2.getModel();
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/yatharth","root","abc");
    Statement stmt=con.createStatement();
    String query="Select * FROM dthcreditcardno;";
    ResultSet rs=stmt.executeQuery(query);
    while(rs.next()){
 String ccn=rs.getString("creditcardno");
model.addRow(new Object[]{ccn});
    }
     rs.close();
     stmt.close();
     con.close();
}
catch(Exception e)
    {
    JoptionPane.showMessageDialog(null,e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_show1dthActionPerformed

    private void dccnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dccnActionPerformed
String str=t2.getText();
if(str.isEmpty()){
JOptionPane.showMessageDialog(null,"Please enter your creditcardno");

}
else
{


 DefaultTableModel model=(DefaultTableModel)tb2.getModel();
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/yatharth","root","abc");
    Statement stmt=con.createStatement();
    String query="Insert into dthcreditcardno values '"+str+"';";
stmt.executeUpdate(query);
}
    catch(Exception e)
    {
    JoptionPane.showMessageDialog(null,"Error in connectivity");
}


     this.dispose();
b10 object = new b10();
object.setVisible(true);
}
// TODO add your handling code here:
    }//GEN-LAST:event_dccnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new b14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dccn;
    private javax.swing.JButton ddcn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton show1dth;
    private javax.swing.JButton showdth;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    // End of variables declaration//GEN-END:variables

}
