/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yatharth bansal
 */
import javax.swing.JOptionPane;
public class b6 extends javax.swing.JFrame {

    /**
     * Creates new form b6
     */
    public b6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobiledebitcard = new javax.swing.JButton();
        mobilecreditcard = new javax.swing.JButton();
        dthdebitcard = new javax.swing.JButton();
        dthcreditcard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("freecharge.");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Total Payment Amount Rs. -");

        jLabel3.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Pay For The Trasection Using Creditor Any Of The Other Payment Option .");

        mobiledebitcard.setBackground(new java.awt.Color(51, 51, 255));
        mobiledebitcard.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        mobiledebitcard.setForeground(new java.awt.Color(102, 0, 0));
        mobiledebitcard.setText("mobile DEBIT CARD.");
        mobiledebitcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiledebitcardActionPerformed(evt);
            }
        });

        mobilecreditcard.setBackground(new java.awt.Color(51, 51, 255));
        mobilecreditcard.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        mobilecreditcard.setForeground(new java.awt.Color(102, 0, 0));
        mobilecreditcard.setText("mobile CREDIT CARD.");
        mobilecreditcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilecreditcardActionPerformed(evt);
            }
        });

        dthdebitcard.setBackground(new java.awt.Color(51, 51, 255));
        dthdebitcard.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        dthdebitcard.setForeground(new java.awt.Color(204, 0, 204));
        dthdebitcard.setText("DTH DEBIT CARD");
        dthdebitcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dthdebitcardActionPerformed(evt);
            }
        });

        dthcreditcard.setBackground(new java.awt.Color(51, 51, 255));
        dthcreditcard.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        dthcreditcard.setForeground(new java.awt.Color(204, 0, 204));
        dthcreditcard.setText("DTH CREDIT CARD");
        dthcreditcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dthcreditcardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mobiledebitcard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mobilecreditcard)
                        .addGap(213, 213, 213)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dthcreditcard, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(dthdebitcard, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobiledebitcard)
                    .addComponent(dthdebitcard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilecreditcard)
                    .addComponent(dthcreditcard, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilecreditcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilecreditcardActionPerformed
String str=t1.getText();
if(str.isEmpty())
{
    JOptionPane.showMessageDialog(null,"please enter payment amount" );
}
      this.dispose();
b9 object = new b9();
object.setVisible(true);        
          
        
        
        // TODO add your handling code here:
}//GEN-LAST:event_mobilecreditcardActionPerformed

    private void mobiledebitcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiledebitcardActionPerformed
String str=t1.getText();
if(str.isEmpty())
{
    JOptionPane.showMessageDialog(null,"please enter payment amount" );
}
this.dispose();
b9 object = new b9();
object.setVisible(true);        

        
        
        // TODO add your handling code here:
}//GEN-LAST:event_mobiledebitcardActionPerformed

    private void dthdebitcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dthdebitcardActionPerformed
String str=t1.getText();
if(str.isEmpty())
{
    JOptionPane.showMessageDialog(null,"please enter payment amount" );
}
this.dispose();
b15 object = new b15();
object.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_dthdebitcardActionPerformed

    private void dthcreditcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dthcreditcardActionPerformed
String str=t1.getText();
if(str.isEmpty())
{
    JOptionPane.showMessageDialog(null,"please enter payment amount" );
}
      this.dispose();
b15 object = new b15();
object.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_dthcreditcardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(b6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(b6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(b6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(b6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new b6().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dthcreditcard;
    private javax.swing.JButton dthdebitcard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mobilecreditcard;
    private javax.swing.JButton mobiledebitcard;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
